//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add an external login.
        /// </summary>
        public static string AddAnExternalLogin {
            get {
                return ResourceManager.GetString("AddAnExternalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 50 characters.
        /// </summary>
        public static string AddressLong {
            get {
                return ResourceManager.GetString("AddressLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address is required.
        /// </summary>
        public static string AddressRequired {
            get {
                return ResourceManager.GetString("AddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unknown error occurred. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string AnUnknownErrorOccurred {
            get {
                return ResourceManager.GetString("AnUnknownErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate your.
        /// </summary>
        public static string AssociateYour {
            get {
                return ResourceManager.GetString("AssociateYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Association Form.
        /// </summary>
        public static string AssociationForm {
            get {
                return ResourceManager.GetString("AssociationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A user name for that e-mail address already exists. Please enter a different e-mail address..
        /// </summary>
        public static string AUserNameForThatEmailAddressAlreadyExists {
            get {
                return ResourceManager.GetString("AUserNameForThatEmailAddressAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse.
        /// </summary>
        public static string Browse {
            get {
                return ResourceManager.GetString("Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse cities.
        /// </summary>
        public static string BrowseCities {
            get {
                return ResourceManager.GetString("BrowseCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse continents.
        /// </summary>
        public static string BrowseContinents {
            get {
                return ResourceManager.GetString("BrowseContinents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse countries.
        /// </summary>
        public static string BrowseCountries {
            get {
                return ResourceManager.GetString("BrowseCountries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse faculties.
        /// </summary>
        public static string BrowseFaculties {
            get {
                return ResourceManager.GetString("BrowseFaculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse universities.
        /// </summary>
        public static string BrowseUniversities {
            get {
                return ResourceManager.GetString("BrowseUniversities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password Form.
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cities.
        /// </summary>
        public static string cities {
            get {
                return ResourceManager.GetString("cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string CityTitle {
            get {
                return ResourceManager.GetString("CityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 20 characters.
        /// </summary>
        public static string CityTitleLong {
            get {
                return ResourceManager.GetString("CityTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City is required.
        /// </summary>
        public static string CityTitleRequired {
            get {
                return ResourceManager.GetString("CityTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm new password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contacts.
        /// </summary>
        public static string Contacts {
            get {
                return ResourceManager.GetString("Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to continents.
        /// </summary>
        public static string continents {
            get {
                return ResourceManager.GetString("continents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent.
        /// </summary>
        public static string ContinentTitle {
            get {
                return ResourceManager.GetString("ContinentTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 20 characters.
        /// </summary>
        public static string ContinentTitleLong {
            get {
                return ResourceManager.GetString("ContinentTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continent is required.
        /// </summary>
        public static string ContinentTitleRequired {
            get {
                return ResourceManager.GetString("ContinentTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to countries.
        /// </summary>
        public static string countries {
            get {
                return ResourceManager.GetString("countries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string CountryTitle {
            get {
                return ResourceManager.GetString("CountryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 20 characters.
        /// </summary>
        public static string CountryTitleLong {
            get {
                return ResourceManager.GetString("CountryTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country is required.
        /// </summary>
        public static string CountryTitleRequired {
            get {
                return ResourceManager.GetString("CountryTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to credential from your account.
        /// </summary>
        public static string CredentialFromYourAccount {
            get {
                return ResourceManager.GetString("CredentialFromYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Database(CRUD).
        /// </summary>
        public static string DataBase {
            get {
                return ResourceManager.GetString("DataBase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string DegreeTitle {
            get {
                return ResourceManager.GetString("DegreeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter faculty.
        /// </summary>
        public static string EnterFaculty {
            get {
                return ResourceManager.GetString("EnterFaculty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter specialization.
        /// </summary>
        public static string EnterSpecialization {
            get {
                return ResourceManager.GetString("EnterSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter university.
        /// </summary>
        public static string EnterUniversity {
            get {
                return ResourceManager.GetString("EnterUniversity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to faculties.
        /// </summary>
        public static string faculties {
            get {
                return ResourceManager.GetString("faculties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty description.
        /// </summary>
        public static string FacultyDescription {
            get {
                return ResourceManager.GetString("FacultyDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 10000 characters.
        /// </summary>
        public static string FacultyDescriptionLong {
            get {
                return ResourceManager.GetString("FacultyDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty title is required.
        /// </summary>
        public static string FacultyDescriptionRequired {
            get {
                return ResourceManager.GetString("FacultyDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty.
        /// </summary>
        public static string FacultyTitle {
            get {
                return ResourceManager.GetString("FacultyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 80 characters.
        /// </summary>
        public static string FacultyTitleLong {
            get {
                return ResourceManager.GetString("FacultyTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faculty title is required.
        /// </summary>
        public static string FacultyTitleRequired {
            get {
                return ResourceManager.GetString("FacultyTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 free educational websites.
        /// </summary>
        public static string FreeEduWeb {
            get {
                return ResourceManager.GetString("FreeEduWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1100 free online courses.
        /// </summary>
        public static string FreeOnlCour {
            get {
                return ResourceManager.GetString("FreeOnlCour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to if you don&apos;t have an account..
        /// </summary>
        public static string IfYouDontHaveAnAccount {
            get {
                return ResourceManager.GetString("IfYouDontHaveAnAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a portal where you can find info about faculties around the world to help you decide where to study. To begin, select Browse from the navbar or enter a desired faculty/study title or part of it into the search box..
        /// </summary>
        public static string Instructions {
            get {
                return ResourceManager.GetString("Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Links.
        /// </summary>
        public static string Links {
            get {
                return ResourceManager.GetString("Links", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in.
        /// </summary>
        public static string LogIn {
            get {
                return ResourceManager.GetString("LogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Failure.
        /// </summary>
        public static string LoginFailure {
            get {
                return ResourceManager.GetString("LoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in Form.
        /// </summary>
        public static string LogInForm {
            get {
                return ResourceManager.GetString("LogInForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using another service.
        /// </summary>
        public static string LogInUsingAnotherService {
            get {
                return ResourceManager.GetString("LogInUsingAnotherService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log in using your.
        /// </summary>
        public static string LogInUsingYour {
            get {
                return ResourceManager.GetString("LogInUsingYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Account.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        public static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to password so you can log in without an external login..
        /// </summary>
        public static string PasswordSoYouCanLogIn {
            get {
                return ResourceManager.GetString("PasswordSoYouCanLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 16 char.
        /// </summary>
        public static string PhoneNumberLong {
            get {
                return ResourceManager.GetString("PhoneNumberLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number is required.
        /// </summary>
        public static string PhoneNumberRequired {
            get {
                return ResourceManager.GetString("PhoneNumberRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a user name for this site below and click the Confirm button to finish logging in..
        /// </summary>
        public static string PleaseEnterUserName {
            get {
                return ResourceManager.GetString("PleaseEnterUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poll.
        /// </summary>
        public static string Poll {
            get {
                return ResourceManager.GetString("Poll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered external logins.
        /// </summary>
        public static string RegisteredExternalLogins {
            get {
                return ResourceManager.GetString("RegisteredExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Form.
        /// </summary>
        public static string RegistrationForm {
            get {
                return ResourceManager.GetString("RegistrationForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me?.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove this.
        /// </summary>
        public static string RemoveThis {
            get {
                return ResourceManager.GetString("RemoveThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Where2Study.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search results.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from.
        /// </summary>
        public static string SelectFrom {
            get {
                return ResourceManager.GetString("SelectFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select from.
        /// </summary>
        public static string SelectFromb {
            get {
                return ResourceManager.GetString("SelectFromb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        public static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Password Form.
        /// </summary>
        public static string SetPasswordForm {
            get {
                return ResourceManager.GetString("SetPasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authentication provider returned an error. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string TheAuthenticationProviderReturnedAnError {
            get {
                return ResourceManager.GetString("TheAuthenticationProviderReturnedAnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The current password is incorrect or the new password is invalid..
        /// </summary>
        public static string TheCurrentPasswordIsIncorrect {
            get {
                return ResourceManager.GetString("TheCurrentPasswordIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The e-mail address provided is invalid. Please check the value and try again..
        /// </summary>
        public static string TheEmailAddressProvidedIsInvalid {
            get {
                return ResourceManager.GetString("TheEmailAddressProvidedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The external login was removed..
        /// </summary>
        public static string TheExternalLoginWasRemoved {
            get {
                return ResourceManager.GetString("TheExternalLoginWasRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The new password and confirmation password do not match..
        /// </summary>
        public static string TheNewPasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("TheNewPasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and confirmation password do not match..
        /// </summary>
        public static string ThePasswordAndConfirmationPasswordDoNotMatch {
            get {
                return ResourceManager.GetString("ThePasswordAndConfirmationPasswordDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password provided is invalid. Please enter a valid password value..
        /// </summary>
        public static string ThePasswordProvidedIsInvalid {
            get {
                return ResourceManager.GetString("ThePasswordProvidedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval answer provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ThePasswordRetrievalAnswerProvidedIsInvalid {
            get {
                return ResourceManager.GetString("ThePasswordRetrievalAnswerProvidedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password retrieval question provided is invalid. Please check the value and try again..
        /// </summary>
        public static string ThePasswordRetrievalQuestionProvidedIsInvalid {
            get {
                return ResourceManager.GetString("ThePasswordRetrievalQuestionProvidedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user creation request has been canceled. Please verify your entry and try again. If the problem persists, please contact your system administrator..
        /// </summary>
        public static string TheUserCreationRequestHasBeenCanceled {
            get {
                return ResourceManager.GetString("TheUserCreationRequestHasBeenCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user name provided is invalid. Please check the value and try again..
        /// </summary>
        public static string TheUserNameProvidedIsInvalid {
            get {
                return ResourceManager.GetString("TheUserNameProvidedIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create local account. An account with the name \&quot;{0}\&quot; may already exist..
        /// </summary>
        public static string UnableToCreateLocalAccountAlreadyExists {
            get {
                return ResourceManager.GetString("UnableToCreateLocalAccountAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to universities.
        /// </summary>
        public static string universities {
            get {
                return ResourceManager.GetString("universities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University description.
        /// </summary>
        public static string UniversityDescription {
            get {
                return ResourceManager.GetString("UniversityDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 10000 characters.
        /// </summary>
        public static string UniversityDescriptionLong {
            get {
                return ResourceManager.GetString("UniversityDescriptionLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University title is required.
        /// </summary>
        public static string UniversityDescriptionRequired {
            get {
                return ResourceManager.GetString("UniversityDescriptionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University.
        /// </summary>
        public static string UniversityTitle {
            get {
                return ResourceManager.GetString("UniversityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 80 characters.
        /// </summary>
        public static string UniversityTitleLong {
            get {
                return ResourceManager.GetString("UniversityTitleLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to University title is required.
        /// </summary>
        public static string UniversityTitleRequired {
            get {
                return ResourceManager.GetString("UniversityTitleRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful login with service..
        /// </summary>
        public static string UnsuccessfulLoginWithService {
            get {
                return ResourceManager.GetString("UnsuccessfulLoginWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use a local account to log in..
        /// </summary>
        public static string UseALocalAccountToLogIn {
            get {
                return ResourceManager.GetString("UseALocalAccountToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use another service to log in..
        /// </summary>
        public static string UseAnotherServiceToLogIn {
            get {
                return ResourceManager.GetString("UseAnotherServiceToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name already exists. Please enter a different user name..
        /// </summary>
        public static string UserNameAlreadyExists {
            get {
                return ResourceManager.GetString("UserNameAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site.
        /// </summary>
        public static string WebSite {
            get {
                return ResourceManager.GetString("WebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Must be less then 50 characters.
        /// </summary>
        public static string WebSiteLong {
            get {
                return ResourceManager.GetString("WebSiteLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web site is required.
        /// </summary>
        public static string WebSiteRequired {
            get {
                return ResourceManager.GetString("WebSiteRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Where2Study web site,.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Where 2 Study Team.
        /// </summary>
        public static string Where2StudyTeam {
            get {
                return ResourceManager.GetString("Where2StudyTeam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have a local password for this site. Add a local.
        /// </summary>
        public static string YouDoNotHaveALocalPassword {
            get {
                return ResourceManager.GetString("YouDoNotHaveALocalPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;re logged in as.
        /// </summary>
        public static string YoureLoggedInAs {
            get {
                return ResourceManager.GetString("YoureLoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed..
        /// </summary>
        public static string YourPasswordHasBeenChanged {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been set..
        /// </summary>
        public static string YourPasswordHasBeenSet {
            get {
                return ResourceManager.GetString("YourPasswordHasBeenSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You&apos;ve successfully authenticated with.
        /// </summary>
        public static string YouveSuccessfullyAuthenticatedWith {
            get {
                return ResourceManager.GetString("YouveSuccessfullyAuthenticatedWith", resourceCulture);
            }
        }
    }
}
