<?xml version="1.0" encoding="utf-8"?><Database Name="w2sDB" Class="w2sDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=(localDB)\v11.0;AttachDbFilename=|DataDirectory|\w2s.mdf;Initial Catalog=w2sDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="w2sDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.drzava" Member="drzavas">
    <Type Name="drzava">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_kontinent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="drzava_drzava_tekst" Member="drzava_teksts" ThisKey="id" OtherKey="id_drzava" Type="drzava_tekst" />
      <Association Name="drzava_grad" Member="grads" ThisKey="id" OtherKey="id_drzava" Type="grad" />
      <Association Name="kontinent_drzava" Member="kontinent" ThisKey="id_kontinent" OtherKey="id" Type="kontinent" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.sveuciliste_tekst" Member="sveuciliste_teksts">
    <Type Name="sveuciliste_tekst">
      <Column Name="id_sveuciliste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naziv" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="jezik_sveuciliste_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="sveuciliste_sveuciliste_tekst" Member="sveuciliste" ThisKey="id_sveuciliste" OtherKey="id" Type="sveuciliste" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.drzava_tekst" Member="drzava_teksts">
    <Type Name="drzava_tekst">
      <Column Name="id_drzava" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naziv" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="drzava_drzava_tekst" Member="drzava" ThisKey="id_drzava" OtherKey="id" Type="drzava" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_drzava_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.fakultet" Member="fakultets">
    <Type Name="fakultet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_grad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adresa_fakulteta" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="broj_telefona" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="id_sveuciliste" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="web" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="slika" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="fakultet_fakultet_tekst" Member="fakultet_teksts" ThisKey="id" OtherKey="id_fakultet" Type="fakultet_tekst" />
      <Association Name="fakultet_smjer" Member="smjers" ThisKey="id" OtherKey="id_fakultet" Type="smjer" />
      <Association Name="grad_fakultet" Member="grad" ThisKey="id_grad" OtherKey="id" Type="grad" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="sveuciliste_fakultet" Member="sveuciliste" ThisKey="id_sveuciliste" OtherKey="id" Type="sveuciliste" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.fakultet_tekst" Member="fakultet_teksts">
    <Type Name="fakultet_tekst">
      <Column Name="id_fakultet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naziv" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="fakultet_fakultet_tekst" Member="fakultet" ThisKey="id_fakultet" OtherKey="id" Type="fakultet" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_fakultet_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.grad" Member="grads">
    <Type Name="grad">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_drzava" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="grad_fakultet" Member="fakultets" ThisKey="id" OtherKey="id_grad" Type="fakultet" />
      <Association Name="grad_grad_tekst" Member="grad_teksts" ThisKey="id" OtherKey="id_grad" Type="grad_tekst" />
      <Association Name="grad_sveuciliste" Member="sveucilistes" ThisKey="id" OtherKey="id_grad" Type="sveuciliste" />
      <Association Name="drzava_grad" Member="drzava" ThisKey="id_drzava" OtherKey="id" Type="drzava" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.grad_tekst" Member="grad_teksts">
    <Type Name="grad_tekst">
      <Column Name="id_grad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naziv" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="opis" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="grad_grad_tekst" Member="grad" ThisKey="id_grad" OtherKey="id" Type="grad" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_grad_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.jezik" Member="jeziks">
    <Type Name="jezik">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="kratica" Type="System.String" DbType="VarChar(5)" CanBeNull="true" />
      <Column Name="ime_jezika" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="jezik_sveuciliste_tekst" Member="sveuciliste_teksts" ThisKey="id" OtherKey="id_jezik" Type="sveuciliste_tekst" />
      <Association Name="jezik_drzava_tekst" Member="drzava_teksts" ThisKey="id" OtherKey="id_jezik" Type="drzava_tekst" />
      <Association Name="jezik_fakultet_tekst" Member="fakultet_teksts" ThisKey="id" OtherKey="id_jezik" Type="fakultet_tekst" />
      <Association Name="jezik_grad_tekst" Member="grad_teksts" ThisKey="id" OtherKey="id_jezik" Type="grad_tekst" />
      <Association Name="jezik_jezik_tekst" Member="jezik_teksts" ThisKey="id" OtherKey="id_jezik" Type="jezik_tekst" />
      <Association Name="jezik_kontinent_tekst" Member="kontinent_teksts" ThisKey="id" OtherKey="id_jezik" Type="kontinent_tekst" />
      <Association Name="jezik_predmet_tekst" Member="predmet_teksts" ThisKey="id" OtherKey="id_jezik" Type="predmet_tekst" />
      <Association Name="jezik_smjer_tekst" Member="smjer_teksts" ThisKey="id" OtherKey="id_jezik" Type="smjer_tekst" />
      <Association Name="jezik_stupanj_tekst" Member="stupanj_teksts" ThisKey="id" OtherKey="id_jezik" Type="stupanj_tekst" />
    </Type>
  </Table>
  <Table Name="dbo.jezik_tekst" Member="jezik_teksts">
    <Type Name="jezik_tekst">
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tekst" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="id_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="jezik_jezik_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.kontinent" Member="kontinents">
    <Type Name="kontinent">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="kontinent_drzava" Member="drzavas" ThisKey="id" OtherKey="id_kontinent" Type="drzava" />
      <Association Name="kontinent_kontinent_tekst" Member="kontinent_teksts" ThisKey="id" OtherKey="id_kontinent" Type="kontinent_tekst" />
    </Type>
  </Table>
  <Table Name="dbo.kontinent_tekst" Member="kontinent_teksts">
    <Type Name="kontinent_tekst">
      <Column Name="id_kontinent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tekst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="kontinent_kontinent_tekst" Member="kontinent" ThisKey="id_kontinent" OtherKey="id" Type="kontinent" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_kontinent_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.predmet" Member="predmets">
    <Type Name="predmet">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ects" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Column Name="god_studija" Type="System.Int16" DbType="SmallInt" CanBeNull="true" />
      <Association Name="predmet_predmet_tekst" Member="predmet_teksts" ThisKey="id" OtherKey="id_predmet" Type="predmet_tekst" />
      <Association Name="predmet_smjer_predmet" Member="smjer_predmets" ThisKey="id" OtherKey="id_predmet" Type="smjer_predmet" />
    </Type>
  </Table>
  <Table Name="dbo.predmet_tekst" Member="predmet_teksts">
    <Type Name="predmet_tekst">
      <Column Name="id_predmet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tekst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="predmet_predmet_tekst" Member="predmet" ThisKey="id_predmet" OtherKey="id" Type="predmet" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_predmet_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.smjer" Member="smjers">
    <Type Name="smjer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_fakultet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="smjer_smjer_predmet" Member="smjer_predmets" ThisKey="id" OtherKey="id_smjer" Type="smjer_predmet" />
      <Association Name="smjer_smjer_tekst" Member="smjer_teksts" ThisKey="id" OtherKey="id_smjer" Type="smjer_tekst" />
      <Association Name="smjer_stupanj_smjer" Member="stupanj_smjers" ThisKey="id" OtherKey="id_smjer" Type="stupanj_smjer" />
      <Association Name="fakultet_smjer" Member="fakultet" ThisKey="id_fakultet" OtherKey="id" Type="fakultet" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.smjer_predmet" Member="smjer_predmets">
    <Type Name="smjer_predmet">
      <Column Name="id_smjer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_predmet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="predmet_smjer_predmet" Member="predmet" ThisKey="id_predmet" OtherKey="id" Type="predmet" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="smjer_smjer_predmet" Member="smjer" ThisKey="id_smjer" OtherKey="id" Type="smjer" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.smjer_tekst" Member="smjer_teksts">
    <Type Name="smjer_tekst">
      <Column Name="id_smjer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tekst" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Association Name="smjer_smjer_tekst" Member="smjer" ThisKey="id_smjer" OtherKey="id" Type="smjer" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_smjer_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.stupanj" Member="stupanjs">
    <Type Name="stupanj">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="trajanje" Type="System.Byte" DbType="TinyInt" CanBeNull="true" />
      <Association Name="stupanj_stupanj_smjer" Member="stupanj_smjers" ThisKey="id" OtherKey="id_stupanj" Type="stupanj_smjer" />
      <Association Name="stupanj_stupanj_tekst" Member="stupanj_teksts" ThisKey="id" OtherKey="id_stupanj" Type="stupanj_tekst" />
    </Type>
  </Table>
  <Table Name="dbo.stupanj_smjer" Member="stupanj_smjers">
    <Type Name="stupanj_smjer">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_stupanj" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_smjer" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="smjer_stupanj_smjer" Member="smjer" ThisKey="id_smjer" OtherKey="id" Type="smjer" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="stupanj_stupanj_smjer" Member="stupanj" ThisKey="id_stupanj" OtherKey="id" Type="stupanj" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.stupanj_tekst" Member="stupanj_teksts">
    <Type Name="stupanj_tekst">
      <Column Name="id_stupanj" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="id_jezik" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="naziv" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Association Name="stupanj_stupanj_tekst" Member="stupanj" ThisKey="id_stupanj" OtherKey="id" Type="stupanj" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="jezik_stupanj_tekst" Member="jezik" ThisKey="id_jezik" OtherKey="id" Type="jezik" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
  <Table Name="dbo.sveuciliste" Member="sveucilistes">
    <Type Name="sveuciliste">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_grad" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="adresa_sveucilista" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="broj_telefona" Type="System.String" DbType="VarChar(32)" CanBeNull="true" />
      <Column Name="web" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="sveuciliste_sveuciliste_tekst" Member="sveuciliste_teksts" ThisKey="id" OtherKey="id_sveuciliste" Type="sveuciliste_tekst" />
      <Association Name="sveuciliste_fakultet" Member="fakultets" ThisKey="id" OtherKey="id_sveuciliste" Type="fakultet" />
      <Association Name="grad_sveuciliste" Member="grad" ThisKey="id_grad" OtherKey="id" Type="grad" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
</Database>